### PR TITLE
Allow html in text messages, for creating for instance links

### PR DESCRIPTION
**Pull request by carlosrgzm**
Remove htmlentites from the message to allow links in the notification's messages

### CODE REVIEW

**Comment by thunder87** [comment]
thanks a lot man, no worries

**Comment by stevevg** [comment]
This causes errors when the notification message actually contains single quote character (i.e. passing a string cotaining the word "D'Anna" - without double quotes - throws an error).

**Comment by thunder87** [comment]
**stefanopallicca**
Just escape that character, i'm guessing that you are getting the parameter from a string.
Toastr::success("Welcome ".htmlspecialchars($user->firstname, ENT_QUOTES));

**Comment by stevevg** [comment]
That's a good point. 
I suggest to review the documentation, adding a warning to escape characters in case of a string that may contain the single quote char.
However, IMHO a method to automatically tell if a string contains HTML or not, would be preferrable.
Alternatively, a new parameter could be added to the info|error|success|warning functions, indicating if the string should be escaped or not.
I may work on this if you think could be useful....

**Pull request merged**
